# docker-compose.yml
services:
  excalidraw:
    image: excalidraw/excalidraw@sha256:f7ee194addd607bf831d2af0f0a34463dd4225e426cf35199ef0b12a803398e9
    container_name: excalidraw
    ports:
      - "${HOST_PORT:-3030}:80" # Loads port from .env, otherwises defaults to 3030
    restart: unless-stopped
    # Ressource cap
    mem_limit: 256
    cpus: 1
    read_only: true # Mount the container's root filesystem as read-only
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs: # Set writable RAM-backed scratch paths for nginx needs despite read_only: true
      - /var/cache/nginx
      - /var/run
      - /tmp
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
